# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d41fec4cbdacbd0bd02f2a1070680a6d5d63bbc4ed8bfd38c39e23581906dce1f41a31fbfdc1cd7558d5587ffaeae05b701000014ffae07662d102b26ca0cb51

test:
  secret_key_base: 438f68a5c9a45c3dfda96bd100ad417cc18b0acac5d48058979fb0fa0f9d73b74582abe016b02fee7c6b15f2b919b8aa28e70a64b677bcf724e95567d8311966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
